// Questions people really ask, with the article that should answer them.
// Written separately from the articles (different words where possible,
// typos included) to measure how well search finds the right one.

module.exports = {
    staff: [
        ["how do I get around the app", "getting-started"],
        ["is there a keyboard shortcut to search", "getting-started"],
        ["switch to dark mode", "getting-started"],
        ["what do the numbers on the home page mean", "dashboard"],
        ["make a quotation for a client", "create-quote"],
        ["how long is a quote valid", "create-quote"],
        ["send an offer to a customer", "create-quote"],
        ["client said yes to the quote, what now", "convert-quote"],
        ["turn quote into order", "convert-quote"],
        ["custmer refused the quote", "convert-quote"],
        ["how to create a new order", "create-order"],
        ["sell products to a customer", "create-order"],
        ["why can't I order more than the stock", "create-order"],
        ["how do I mark an order as delivered", "order-statuses"],
        ["cancel an order", "order-statuses"],
        ["what does processing mean", "order-statuses"],
        ["print the invoice", "invoices"],
        ["what vat rate is used", "invoices"],
        ["when is payment due", "invoices"],
        ["customer paid by cheque how do I record it", "record-payment"],
        ["record a partial paymnt", "record-payment"],
        ["I entered a payment twice", "record-payment"],
        ["who owes us money", "receivables"],
        ["list of overdue invoices", "receivables"],
        ["export unpaid invoices for the accountant", "receivables"],
        ["why does this invoice say 72% late risk", "late-payment-risk"],
        ["which invoices will probably be paid late", "late-payment-risk"],
        ["customer sent back damaged goods", "returns"],
        ["make a credit note", "returns"],
        ["refund a customer", "returns"],
        ["add a new client", "customers"],
        ["where is the order history of a customer", "customers"],
        ["let a customer order online", "portal-access"],
        ["create a login for a client", "portal-access"],
        ["give a special price to one customer", "pricing-rules"],
        ["discount for buying in bulk", "pricing-rules"],
        ["how is the price calculated", "pricing-rules"],
        ["add a product to the catalogue", "products"],
        ["delete a product", "products"],
        ["what is the reorder point", "products"],
        ["the stock count is wrong", "stock"],
        ["some items were stolen, fix the quantity", "stock"],
        ["what do I need to buy from suppliers", "reorder-suggestions"],
        ["why is this product suggested for reordering", "reorder-suggestions"],
        ["order goods from a supplier", "purchase-orders"],
        ["the delivery arrived, add it to stock", "purchase-orders"],
        ["supplier lead time", "suppliers"],
        ["profit margin by product", "reports"],
        ["sales report for last month", "reports"],
        ["how many units will we sell next month", "demand-forecast"],
        ["how long will my stock last", "demand-forecast"],
        ["what else can I sell to this customer", "recommendations"],
        ["can I trust the AI models", "models"],
        ["how accurate are the predictions", "models"],
        ["I can't see the reports page", "roles"],
        ["what can a warehouse user do", "roles"],
        ["add a new employee account", "users"],
        ["reset a colleague's password", "users"],
        ["who changed this customer", "audit-log"],
        ["see failed login attempts", "audit-log"],
        ["send the invoice to the client by email", "emails"],
        ["does the app remind customers before they have to pay", "emails"],
        // French
        ["comment créer un devis", "create-quote"],
        ["le client a accepté le devis", "convert-quote"],
        ["créer une nouvelle commande", "create-order"],
        ["annuler une commande", "order-statuses"],
        ["imprimer la facure", "invoices"],
        ["enregistrer un paiement par virement", "record-payment"],
        ["quels clients ont des impayés", "receivables"],
        ["faire un avoir pour un retour", "returns"],
        ["donner un prix spécial à un client", "pricing-rules"],
        ["corriger le stock d'un produit", "stock"],
        ["commander chez un fournisseur", "purchase-orders"],
        ["voir la marge par catégorie", "reports"],
        ["ajouter un utilisateur", "users"],
        ["envoyer le devis par mail au client", "emails"],
        // Arabic
        ["كيف أنشئ عرض سعر", "create-quote"],
        ["كيف أسجل أداء الزبون", "record-payment"],
        ["طباعة الفاتورة", "invoices"],
        ["إلغاء طلبية", "order-statuses"],
        ["إرجاع سلعة تالفة", "returns"],
        ["تصحيح المخزون", "stock"],
        ["من يدين لنا بالمال", "receivables"],
        ["إضافة زبون جديد", "customers"],
        ["تقرير المبيعات والهامش", "reports"],
        ["إرسال الفاتورة بالبريد إلى الزبون", "emails"]
    ],
    client: [
        ["what can I do here", "portal-start"],
        ["how do I order", "portal-order"],
        ["add products to my cart", "portal-order"],
        ["checkout", "portal-order"],
        ["why is the price crossed out", "portal-prices"],
        ["is vat included in the price", "portal-prices"],
        ["cheaper if I buy more", "portal-prices"],
        ["download my invoice", "portal-invoices"],
        ["how much do I owe", "portal-invoices"],
        ["I paid but it still says unpaid", "portal-invoices"],
        ["order the same thing as last time", "portal-reorder"],
        ["accept the quote you sent", "portal-quotes"],
        ["decline a quotation", "portal-quotes"],
        ["return a damaged product", "portal-returns"],
        ["why are these products recommended", "portal-recommended"],
        ["change my password", "portal-account"],
        ["forgot my pasword", "portal-account"],
        ["switch the language to french", "portal-language"],
        ["comment passer une commande", "portal-order"],
        ["télécharger ma facture", "portal-invoices"],
        ["accepter le devis", "portal-quotes"],
        ["changer mon mot de passe", "portal-account"],
        ["كيف أطلب", "portal-order"],
        ["تحميل الفاتورة", "portal-invoices"],
        ["تغيير كلمة المرور", "portal-account"]
    ]
};
